# Generated by Django 5.1.5 on 2025-01-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_autor_options_livro"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="autores",
            field=models.ManyToManyField(related_name="Livros", to="core.autor"),
        ),
    ]
